var = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(var)}')
print(f'É AlphaNumérico? {var.isalnum()}')
print(f'É Alfabético? {var.isalpha()}')
print(f'Está no Código Padrão Americano? {var.isascii()}')
print(f'É Numérico? {var.isnumeric()}')
print(f'É um Dígito? {var.isdigit()}')
print(f'É um número Real? {var.isdecimal()}')
print(f'Está todo em Maiúsculo? {var.isupper()}')
print(f'Está tdo em Minúsculo? {var.islower()}')
print(f'É "Printável" na tela? {var.isprintable()}')
print(f'Contém somente Letras, Números e "Underline"? {var.isidentifier()}')
print(f'É Vazia? {var.isspace()}')
print(f'Está capitalizada? {var.istitle()}')

